package sytemgrade

//list any import classes here.

import bookgengrade.GenreCoeficient;
import rs.sbnz.book_recommender.model.Book;
import rs.sbnz.book_recommender.model.Author;

//declare any global variables here



rule "System Grade with Author Grade"
	agenda-group "Level6"
	no-loop
	salience 10
    when
        $b: Book(bookId: id, title: title, grade: getSystemGrade()) @Watch(!systemGrade)
    	$a: Author(authorGrade: getSystemGrade(), $bookList: books)
    	Long(intValue == 1)from accumulate(Book($bi: this,bookId==id) from $bookList,
	        count($bi))
    then
    	//System.out.println("knjige");
        modify($b){setSystemGrade(0.8 * grade + 0.1 * authorGrade)}

end

rule "Add genre coeficient data to book grade"
	agenda-group "Level7"
	no-loop
	salience 0
    when
        $b: Book(bookId: id, grade: getSystemGrade(), $genList: genres) @Watch(!systemGrade)
        GenreCoeficient(id == bookId, coef: coef, coef > 0)
    then
    	//System.out.println("ulazim stalno " + (1. * coef / $genList.size()));

    	//System.out.println("ulazim stalno coef " + coef);
    	modify($b){setSystemGrade(grade + (1. * coef / $genList.size()))}

end



rule "Halt grading"
	agenda-group "Close"
	no-loop
	salience 0
    when

    then
        drools.halt();
end