import rs.sbnz.book_recommender.model.User
import rs.sbnz.book_recommender.model.Book
import java.util.List;

rule "Filter books based on user age"
  agenda-group "UserAgeFilter"
  no-loop
  when
  $user : User(age : age)
  $userBooksRead: Book(targetAudience != age)
  then
  delete($userBooksRead);
end

/*rule "When user is a young adult"
  agenda-group "UserAgeFilter"
  no-loop
  when
  $book : Book()
  then
  System.out.println($book.getTitle());
end*/
