import rs.sbnz.book_recommender.model.User
import rs.sbnz.book_recommender.model.Book
import rs.sbnz.book_recommender.model.Genre
import java.util.List;

rule "Simple score user read genres"
  agenda-group "GenreScore"
  no-loop
  when
  $user: User()
  $genre: Genre($genre_name: name)
  $book: Book($book_genres: genres, $genre memberOf $book_genres)
  sumReadOfGenre($genre, $user, $num;)
  then
  modify($book){setUserRecommendedScore($book.getUserRecommendedScore() + (0.5+(0.1*$num.doubleValue())))}
end

rule "Test Genre"
  agenda-group "GenreScore"
  no-loop
  when
  $book : Book()
  then
  System.out.println($book.getTitle() + ": " + $book.getUserRecommendedScore());
end

//presek liste, novi rule, query

query sumReadOfGenre(Genre genreParam, User userParam , Number $num)
    $num := Number()
    from accumulate($b:Book(genreParam memberOf genres)
    from userParam.getReadBooks(),
    count($b))
end